require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecipentsController do

  # This should return the minimal set of attributes required to create a valid
  # Recipent. As you add validations to Recipent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecipentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recipents as @recipents" do
      recipent = Recipent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recipents).should eq([recipent])
    end
  end

  describe "GET show" do
    it "assigns the requested recipent as @recipent" do
      recipent = Recipent.create! valid_attributes
      get :show, {:id => recipent.to_param}, valid_session
      assigns(:recipent).should eq(recipent)
    end
  end

  describe "GET new" do
    it "assigns a new recipent as @recipent" do
      get :new, {}, valid_session
      assigns(:recipent).should be_a_new(Recipent)
    end
  end

  describe "GET edit" do
    it "assigns the requested recipent as @recipent" do
      recipent = Recipent.create! valid_attributes
      get :edit, {:id => recipent.to_param}, valid_session
      assigns(:recipent).should eq(recipent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recipent" do
        expect {
          post :create, {:recipent => valid_attributes}, valid_session
        }.to change(Recipent, :count).by(1)
      end

      it "assigns a newly created recipent as @recipent" do
        post :create, {:recipent => valid_attributes}, valid_session
        assigns(:recipent).should be_a(Recipent)
        assigns(:recipent).should be_persisted
      end

      it "redirects to the created recipent" do
        post :create, {:recipent => valid_attributes}, valid_session
        response.should redirect_to(Recipent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recipent as @recipent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recipent.any_instance.stub(:save).and_return(false)
        post :create, {:recipent => {}}, valid_session
        assigns(:recipent).should be_a_new(Recipent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recipent.any_instance.stub(:save).and_return(false)
        post :create, {:recipent => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recipent" do
        recipent = Recipent.create! valid_attributes
        # Assuming there are no other recipents in the database, this
        # specifies that the Recipent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recipent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recipent.to_param, :recipent => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recipent as @recipent" do
        recipent = Recipent.create! valid_attributes
        put :update, {:id => recipent.to_param, :recipent => valid_attributes}, valid_session
        assigns(:recipent).should eq(recipent)
      end

      it "redirects to the recipent" do
        recipent = Recipent.create! valid_attributes
        put :update, {:id => recipent.to_param, :recipent => valid_attributes}, valid_session
        response.should redirect_to(recipent)
      end
    end

    describe "with invalid params" do
      it "assigns the recipent as @recipent" do
        recipent = Recipent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recipent.any_instance.stub(:save).and_return(false)
        put :update, {:id => recipent.to_param, :recipent => {}}, valid_session
        assigns(:recipent).should eq(recipent)
      end

      it "re-renders the 'edit' template" do
        recipent = Recipent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recipent.any_instance.stub(:save).and_return(false)
        put :update, {:id => recipent.to_param, :recipent => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recipent" do
      recipent = Recipent.create! valid_attributes
      expect {
        delete :destroy, {:id => recipent.to_param}, valid_session
      }.to change(Recipent, :count).by(-1)
    end

    it "redirects to the recipents list" do
      recipent = Recipent.create! valid_attributes
      delete :destroy, {:id => recipent.to_param}, valid_session
      response.should redirect_to(recipents_url)
    end
  end

end
